name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - issue/*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    # Pre-installed packages break the environment required to build BCC.
    # That's why I decided to use Docker inside GitHub Actions.
    - run: docker image build -f=build/Dockerfile -t box:latest .
    - run: docker container run --rm --mount type=bind,source="$(pwd)",target=/workspace box:latest go build -o work/nudge .
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: work/nudge

  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
    - name: Generate build number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        prefix: build_number_generator
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: build-${{env.BUILD_NUMBER}}
        release_name: Build ${{env.BUILD_NUMBER}}
        draft: false
        prerelease: false
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}}
        asset_path: ./nudge
        asset_name: nudge.build-${{env.BUILD_NUMBER}}-linux-amd64
        asset_content_type: application/octet-stream
